# Generated by Django 4.2.6 on 2023-10-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_name_product_price_product_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
